site_name: Pisek docs
repo_url: https://github.com/piskoviste/pisek

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: amber
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: amber
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: assets/logo.png
  logo: assets/logo.png

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
