name: Pisek ⏳ CI

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # see https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python for more details
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pisek
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Build dist/
      run: |
        pip install build
        python3 -m build
    - name: Upload dist/
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish:
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/pisek

    permissions:
      id-token: write

    steps:
    - name: Download dist/
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
